/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class serial_ListSerialPorts */

#ifndef _Included_serial_ListSerialPorts
#define _Included_serial_ListSerialPorts
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     serial_ListSerialPorts
 * Method:    enumeratePorts
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_serial_ListSerialPorts_enumeratePorts
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
