/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cam_NativeCamera */

#ifndef _Included_cam_NativeCamera
#define _Included_cam_NativeCamera
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cam_NativeCamera
 * Method:    camSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camSetup
  (JNIEnv *, jclass, jint);

/*
 * Class:     cam_NativeCamera
 * Method:    camStartPreview
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camStartPreview
  (JNIEnv *, jclass, jint);

/*
 * Class:     cam_NativeCamera
 * Method:    camStopPreview
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camStopPreview
  (JNIEnv *, jclass, jint);

/*
 * Class:     cam_NativeCamera
 * Method:    camGetPreviewImage
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camGetPreviewImage
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     cam_NativeCamera
 * Method:    camStartSequence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camStartSequence
  (JNIEnv *, jclass, jint);

/*
 * Class:     cam_NativeCamera
 * Method:    camGetNextSequenceImage
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camGetNextSequenceImage
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     cam_NativeCamera
 * Method:    camStopSequence
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camStopSequence
  (JNIEnv *, jclass, jint);

JNIEXPORT jdouble JNICALL Java_cam_NativeCamera_camGetFramerate
  (JNIEnv *, jclass, jint);

/*
 * Class:     cam_NativeCamera
 * Method:    camClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cam_NativeCamera_camClose
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
