/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class stage_NativeMotor */

#ifndef _Included_stage_NativeMotor
#define _Included_stage_NativeMotor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     stage_NativeMotor
 * Method:    stageConnect
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_stage_NativeMotor_stageConnect
  (JNIEnv *, jclass, jint, jobjectArray stages);

/*
 * Class:     stage_NativeMotor
 * Method:    stageIsReferenceNeeded
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_stage_NativeMotor_stageIsReferenceNeeded
  (JNIEnv *, jclass, jint);

/*
 * Class:     stage_NativeMotor
 * Method:    stageReferenceIfNeeded
 * Signature: ()Z
 */
JNIEXPORT void JNICALL Java_stage_NativeMotor_stageReferenceIfNeeded
  (JNIEnv *, jclass, jint);

/*
 * Class:     stage_NativeMotor
 * Method:    stageGetPosition
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_stage_NativeMotor_stageGetPosition
  (JNIEnv *, jclass, jint);

/*
 * Class:     stage_NativeMotor
 * Method:    stageGetVelocity
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_stage_NativeMotor_stageGetVelocity
  (JNIEnv *, jclass, jint);

/*
 * Class:     stage_NativeMotor
 * Method:    stageIsMoving
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_stage_NativeMotor_stageIsMoving
  (JNIEnv *, jclass, jint);

/*
 * Class:     stage_NativeMotor
 * Method:    stageSetVelocity
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_stage_NativeMotor_stageSetVelocity
  (JNIEnv *, jclass, jint, jdouble);

/*
 * Class:     stage_NativeMotor
 * Method:    stageSetTarget
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_stage_NativeMotor_stageSetTarget
  (JNIEnv *, jclass, jint, jdouble);

JNIEXPORT void JNICALL Java_stage_NativeMotor_stageStopMoving
  (JNIEnv *, jclass, jint);

/*
 * Class:     stage_NativeMotor
 * Method:    stageClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_stage_NativeMotor_stageClose
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
