/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class windows_ToFront */

#ifndef _Included_windows_ToFront
#define _Included_windows_ToFront
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     windows_ToFront
 * Method:    toFront
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_windows_ToFront_toFront
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
